server:
  port: 9997

## H2 Configuration
spring:
  h2:
    console:
      enabled: true
      path: /gadget-console
      settings:
        trace: false
        web-allow-others: false
  datasource:
    url: jdbc:h2:mem:gadget-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: gadgetadmin
    password: ##gadgetpwd
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        use_sql_comments: true
        format_sql: true

springdoc:
  swagger-ui:
    path: /
    operationsSorter: method

## https://swathisprasad.medium.com/automating-code-with-mapstruct-44b8c324a23e
## https://medium.com/1developer/spring-requestparam-vs-queryparam-vs-pathvariable-vs-pathparam-7c5655e541ad
## https://yashodgayashan.medium.com/optional-query-parameters-in-spring-boot-7456cc82d8b9
## https://www.baeldung.com/spring-requestparam-vs-pathvariable